"""Standalone HTML page view of the frozen computation.

A THIRD RENDERER, not a third source of truth. Like `daily_render` and
`email_render` it consumes `brief.compute`'s frozen schema-v2 output and never
fetches, selects, scores, allocates or persists. It exists because the daily
page was being rewritten by hand each morning, and a page regenerated by hand
drifts: the day this renderer was written, the standing instruction for that
rewrite had to repeat "render no share count on an ABSTAIN leg" in capitals
because there was nothing to enforce it. Here it is enforced by construction —
`_alloc_cell` cannot emit a size for an abstained leg, and a test fails if it
ever does.

Pure: give it a digest, get a string. No clock read, no network, no writes.
"""
from __future__ import annotations

import argparse
import json
from html import escape

import daily_render as R
import deepseek_opportunities as O

fmt = R.fmt

# The single place a number becomes text. Keep every figure traceable to the
# frozen digest; never compute a new one here.
ABSTAIN_CELL = '&mdash;'


def _pct(value, spec='.1%'):
    return 'unknown' if value is None else format(value, spec)


def _alloc_cell(leg, key):
    """No size on an abstained leg — enforced, not remembered.

    A row carrying a share count or a dollar figure is an order ticket whatever
    the status column says. That has been acted on twice. The banner did not
    stop it; withholding the number does."""
    if leg.get('status') == 'ABSTAIN' or leg.get(key) in (None, ''):
        return ABSTAIN_CELL
    value = leg[key]
    return f"{value:,.0f}" if key == 'baseline_alloc' else f"{value:g}"


def _is_entry(digest):
    """Is this an executable morning entry, or an informational page?"""
    status = str(digest.get('report_status') or '')
    return status.startswith('ON_TIME') and any(
        leg.get('status') in ('ELIGIBLE', 'SHADOW') for leg in digest['intraday'].get('legs', []))


def _legs_rows(legs):
    if not legs:
        return ('<tr><td colspan="7" class="empty">No baseline legs were selected. '
                'This is not a statement that no opportunity existed — see the coverage note below.</td></tr>')
    out = []
    for leg in legs:
        quote = leg.get('quote') or {}
        out.append(
            '<tr>'
            f'<td><span class="status">{escape(str(leg.get("status","?")))}</span></td>'
            f'<td class="tick">{escape(str(leg.get("ticker","?")))}</td>'
            f'<td>{escape(str(leg.get("side","?")))}</td>'
            f'<td class="num">{fmt(leg.get("signal_reference"))}</td>'
            f'<td class="num">{fmt(leg.get("entry_reference"))}</td>'
            f'<td class="num">{fmt(leg.get("entry_spread_bps"))}</td>'
            f'<td class="num withheld">{_alloc_cell(leg, "baseline_shares")}</td>'
            '</tr>')
        reasons = [r for r in (leg.get('reasons') or []) if r]
        if reasons:
            out.append(f'<tr class="reason"><td></td><td colspan="6">'
                       f'{escape("; ".join(str(r) for r in reasons))}</td></tr>')
        if quote.get('status') and quote['status'] != 'OK':
            out.append(f'<tr class="reason"><td></td><td colspan="6">Quote: '
                       f'{escape(str(quote["status"]))}</td></tr>')
    return '\n'.join(out)


def _calibration_rows(bands):
    out = []
    for band in bands or []:
        rate = band.get('rate')
        out.append(
            '<tr>'
            f'<td>{escape(str(band.get("score_band","?")))}</td>'
            f'<td class="num">{band.get("hits", 0) if band.get("n") else ABSTAIN_CELL}</td>'
            f'<td class="num">{band.get("n", 0)}</td>'
            f'<td class="num">{band.get("sessions", 0)}</td>'
            f'<td class="num">{_pct(rate)}</td>'
            f'<td class="num">{fmt(band.get("mde80_pp"))}</td>'
            '</tr>')
    return '\n'.join(out) or '<tr><td colspan="6" class="empty">No scored bands yet.</td></tr>'


def _ci_figure(rate):
    """The interval against the coin-flip line, positioned on a 30–70% scale.

    One scale places the band, the point and the 50% marker; every label names
    a value the figure actually reaches. Rates outside the scale are clamped so
    a mark never escapes the drawing."""
    lo_hi = rate.get('ci95') or []
    if len(lo_hi) != 2 or rate.get('rate') is None:
        return ('<p class="note">Hit-rate interval unavailable — the record has no '
                'scored legs to bound.</p>')
    span_lo, span_hi = 0.30, 0.70
    def place(value):
        return max(0.0, min(100.0, (min(max(value, span_lo), span_hi) - span_lo) / (span_hi - span_lo) * 100))
    lo, hi = place(lo_hi[0]), place(lo_hi[1])
    point = place(rate['rate'])
    straddles = lo_hi[0] <= 0.5 <= lo_hi[1]
    verdict = ('The 95% interval contains 50%: after '
               f"{rate.get('n', 0)} legs this record is not distinguishable from a coin flip."
               if straddles else
               'The 95% interval excludes 50%.')
    return f'''
    <figure class="ci">
      <div class="ci-track">
        <div class="ci-band" style="left:{lo:.1f}%;width:{max(hi-lo,0.5):.1f}%"></div>
        <div class="ci-point" style="left:{point:.1f}%"></div>
        <div class="ci-coin" style="left:{place(0.5):.1f}%"></div>
        <div class="ci-label" style="left:{lo:.1f}%">{_pct(lo_hi[0])}</div>
        <div class="ci-label ci-mid" style="left:{point:.1f}%">{_pct(rate['rate'])}</div>
        <div class="ci-label" style="left:{hi:.1f}%">{_pct(lo_hi[1])}</div>
        <div class="ci-axis"></div>
      </div>
      <div class="ci-ticks"><span>30%</span><span>40%</span><span>50%</span><span>60%</span><span>70%</span></div>
      <figcaption>{escape(verdict)} Minimum detectable effect at 80% power:
        <strong>{fmt(rate.get('mde80_pp'))} percentage points</strong>, clustered over
        {rate.get('sessions', 0)} sessions. Differences smaller than that are not
        measurable here.</figcaption>
    </figure>'''


LEAN_NOTE = ('A lean is a reading of public evidence, not a recommendation. The model does '
             'not compute indicators, does not see the ledger, and cannot select, size or '
             'rank anything: every technical statement in a rationale is generated by Python '
             'and quoted back to it. Nothing in this section is adopted.')


def _factor_top2(shadow):
    """The factor layer's own top two per side — H1, as registered.

    This is NOT a new ranking invented for the page. `rank_shadow` already
    computes it at MAX_PER_SIDE = 2 from names that cleared BOTH the combined
    score threshold and the lean/sign agreement gate. Rendering it here only
    surfaces a decision the frozen computation already made.

    On a day when nothing clears, this renders the fact that nothing cleared.
    It must never fall back to "the two highest anyway": a top two taken from
    an all-NO_EDGE set is a pick manufactured out of ties, and the engine's
    whole design is that abstention is an answer."""
    h1 = (shadow or {}).get('h1') or {}
    out = []
    for side, key in (('LONG', 'longs'), ('SHORT', 'shorts')):
        for rank, row in enumerate((h1.get(key) or [])[:2], start=1):
            out.append({'side': side, 'rank': rank, 'ticker': row.get('ticker'),
                        'sided': row.get('sided_score'),
                        'combined': row.get('combined_probability'),
                        'quant': row.get('quant_probability'),
                        'spread': row.get('spread_bps'),
                        'reason': row.get('reason')})
    return out


def _nearest_misses(shadow, limit=3):
    """The names that came closest, and which gate stopped each one.

    "Top two: none" is true but tells the reader nothing about whether the day
    was quiet or the gate is unreachable. These rows are NOT picks and are
    ranked by a score that did not qualify — they exist so a reader can see
    where the veto happened. Naming the binding gate matters: on 2026-09-16
    TRP.TO reached sided 0.592 against a 0.55 threshold and was still rejected,
    because the model returned NO_EDGE and the lean gate, not the score, is
    what stopped it."""
    rows = [r for r in (shadow or {}).get('rows') or []
            if r.get('sided_score') is not None and r.get('status') != 'CANDIDATE']
    rows.sort(key=lambda r: -r['sided_score'])
    return rows[:limit]


def _factor_top2_block(top, passes, shadow=None):
    if not top:
        near = _nearest_misses(shadow)
        table = ''
        if near:
            body = ''.join(
                '<tr>'
                f'<td class="tick">{escape(str(r.get("ticker","?")))}</td>'
                f'<td class="num">{fmt(r.get("sided_score"), ".3f")}</td>'
                f'<td class="num">{fmt(r.get("quant_probability"), ".3f")}</td>'
                f'<td class="reasontext">{escape(str(r.get("reason") or ""))}</td>'
                '</tr>' for r in near)
            table = ('<div class="scroll"><table><caption>Not picks. These did not qualify; '
                     'they are shown so the binding gate is visible. A score above the '
                     'threshold can still be rejected — the factor layer requires a '
                     'directional lean that agrees in sign, and an assessment of NO_EDGE '
                     'vetoes the name however high its quantitative score.</caption>'
                     '<thead><tr><th>Name</th><th class="num">Sided</th>'
                     '<th class="num">Quant</th><th>Why it did not qualify</th></tr></thead>'
                     f'<tbody>{body}</tbody></table></div>')
        return ('<p class="note"><strong>Top two: none.</strong> No name cleared both the '
                'combined-score threshold and the lean-agreement gate, so the factor layer '
                'selected nothing on either side. A top two taken from names that did not '
                'clear would be a pick manufactured out of ties — abstention is the answer '
                'here, not a missing one.</p>' + table)
    rows = ''.join(
        '<tr>'
        f'<td>{escape(r["side"])} #{r["rank"]}</td>'
        f'<td class="tick">{escape(str(r["ticker"]))}</td>'
        f'<td class="num">{fmt(r["sided"], ".3f")}</td>'
        f'<td class="num">{fmt(r["combined"], ".3f")}</td>'
        f'<td class="num">{fmt(r["quant"], ".3f")}</td>'
        f'<td class="num">{fmt(r["spread"])}</td>'
        '</tr>' for r in top)
    return ('<h2 class="head" style="font-size:1.2rem;margin-top:2rem">Factor top two per side</h2>'
            '<div class="scroll"><table><caption>H1, as registered: at most two per side, '
            'ranked by sided score, from names that cleared the threshold AND agreed in sign '
            'with their lean. These are shadow research candidates recorded for a forward '
            'study — they do not enter the baseline board, carry no size, and are not '
            'calibrated win probabilities.</caption>'
            '<thead><tr><th>Slot</th><th>Name</th><th class="num">Sided</th>'
            '<th class="num">Combined</th><th class="num">Quant</th>'
            '<th class="num">Spread bps</th></tr></thead>'
            f'<tbody>{rows}</tbody></table></div>')


def _factor_section(intra):
    """The day-99 factor layer. Shadow, unadopted, and never a pick list.

    Rendered whenever the layer has something to say. When it did not run, the
    section states that and why in one line rather than being silently absent —
    a missing section reads as "no signal", which is a different claim from
    "not evaluated"."""
    snap = intra.get('deepseek') or {}
    shadow = snap.get('shadow') or {}
    assessments = snap.get('assessments') or []
    covered, requested = snap.get('covered') or 0, snap.get('requested') or 0
    head = ('<section><h2 class="head">Factor research</h2>'
            '<p class="sub">Shadow · unadopted · changes no selection, size or threshold</p>')

    if not R.factor_reported(intra):
        reason = escape(str(R.factor_note(intra) or 'Not evaluated this session.'))
        return head + f'<ul class="gaps"><li class="g-quiet">{reason}</li></ul></section>'

    passes = len([r for r in (shadow.get('rows') or []) if r.get('status') == 'CANDIDATE'])
    rows = []
    for row in sorted(assessments, key=lambda r: -abs(r.get('sentiment_score') or 0)):
        rows.append(
            '<tr>'
            f'<td class="tick">{escape(str(row.get("ticker","?")))}</td>'
            f'<td>{escape(str(row.get("directional_lean","?")))}</td>'
            f'<td class="num">{fmt(row.get("sentiment_score"), "+.2f")}</td>'
            f'<td class="reasontext">{escape(str(row.get("factor_rationale",""))[:180])}</td>'
            '</tr>')
    table = ('<div class="scroll"><table><thead><tr><th>Name</th><th>Lean</th>'
             '<th class="num">Sentiment</th><th>Rationale — not verified fact</th></tr></thead>'
             f'<tbody>{"".join(rows)}</tbody></table></div>') if rows else ''

    top = _factor_top2(shadow)
    verdict = (f'<p><strong>{passes} name(s) cleared the registered threshold.</strong> '
               + ('Nothing in this section became a candidate, so the shadow arms produce no '
                  'board.' if not passes else
                  'Shadow candidates are recorded for the forward study; they do not enter the '
                  'baseline board.') + '</p>')
    gaps = ''.join(f'<li class="g-quiet">{escape(str(g))}</li>' for g in (snap.get('gaps') or []))
    return (head
            + f'<div class="kv"><div><dt>Model</dt><dd>{escape(str(snap.get("model") or "unavailable"))}'
            f'<small>{escape(str(snap.get("status","?")))}</small></dd></div>'
            f'<div><dt>Assessed</dt><dd>{covered} / {requested}<small>of the staged pool</small></dd></div>'
            f'<div><dt>Threshold passes</dt><dd>{passes}<small>entering nothing</small></dd></div></div>'
            + verdict + _factor_top2_block(top, passes, shadow) + table
            + f'<p class="note">{LEAN_NOTE}</p>'
            + (f'<ul class="gaps">{gaps}</ul>' if gaps else '')
            + '</section>')


OPPORTUNITY_NOTE = (
    'These are the model\'s own picks, not the engine\'s. The engine scores 21 names with a '
    'recorded hit rate behind its number; this asks a 130-name pool a direct question and '
    'prints whatever comes back. The two are shown side by side so they can be compared '
    'GOING FORWARD — there is no forward evidence yet, nothing here is adopted, nothing here '
    'carries a size, and the two numbers are never blended, because averaging a measured '
    'probability with an unmeasured self-report launders the second into the first.')


def _opportunity_rows(comparison):
    verdict_class = {O.AGREE: 'g-accent', O.OPPOSE: 'g-alarm'}
    rows = ''
    for r in (comparison or {}).get('rows') or []:
        cls = verdict_class.get(r['verdict'], 'g-quiet')
        rows += ('<tr>'
                 f'<td>{escape(r["side"])}</td>'
                 f'<td class="tick">{escape(str(r["ticker"]))}</td>'
                 f'<td class="num">{fmt(r["confidence"], ".2f")}</td>'
                 f'<td class="num">{fmt(r["engine_p_sided"], ".3f") if r.get("engine_p_sided") is not None else ABSTAIN_CELL}</td>'
                 f'<td class="{cls}">{escape(r["verdict"])}</td>'
                 f'<td class="reasontext">{escape(str(r.get("reason") or ""))[:200]}</td>'
                 '</tr>')
    return rows


def _opportunities_section(intra):
    """DeepSeek's own top two per side, beside the engine's board.

    Unlike `_factor_section` this is an OPINION, asked for directly. It exists
    because the factor layer answers a narrower question — "is there sentiment
    in these headlines" — and on a commentary feed it abstains almost every day,
    which for six sessions read to the owner as a broken integration rather than
    as the tested abstention it is.

    When the model returns nothing, that is stated as an abstention with its
    control recorded, never as an empty section. A missing section reads as
    "no signal", which is a different claim from "not evaluated"."""
    snap = intra.get('opportunities') or {}
    comparison = snap.get('comparison') or {}
    head = ('<section><h2 class="head">DeepSeek opportunities</h2>'
            '<p class="sub">The model\'s own top 2 per side · shadow · unadopted · no size</p>')
    status = snap.get('status')
    if status not in ('READY', 'NO_OPPORTUNITY'):
        reason = escape(str(snap.get('reason') or 'Not staged this session.'))
        return head + f'<ul class="gaps"><li class="g-quiet">{reason}</li></ul></section>'

    # A ranking asked after the bell is a different instrument from one asked
    # before it: the prior-session indicators are the same, but the answer was
    # formed with the morning already visible to the person who ran it. That
    # distinction belongs on the page, not in the operator's head.
    when = ('asked AFTER the open — diagnostic' if snap.get('diagnostic')
            else 'asked once, pre-open')
    diagnostic_banner = ('<p class="note"><strong>Current-time diagnostic.</strong> This '
                         'ranking was requested after 09:30 ET, so it is not a pre-open '
                         'opinion and is not evidence about the morning. The inputs are still '
                         'previous-session indicators, but the request itself was not blind '
                         'to the day.</p>') if snap.get('diagnostic') else ''
    kv = (diagnostic_banner + f'<div class="kv">'
          f'<div><dt>Model</dt><dd>{escape(str(snap.get("model") or "unavailable"))}'
          f'<small>{escape(when)}</small></dd></div>'
          f'<div><dt>Names offered</dt><dd>{snap.get("considered", 0)}'
          f'<small>carrying complete technicals</small></dd></div>'
          f'<div><dt>Agreement</dt><dd>{comparison.get("agree", 0)} of '
          f'{len(comparison.get("rows") or [])}<small>{comparison.get("oppose", 0)} opposed · '
          f'{comparison.get("unseen", 0)} outside the engine universe</small></dd></div></div>')

    if status == 'NO_OPPORTUNITY':
        return (head + kv + '<p><strong>The model returned no opportunity on either side.</strong> '
                'That is an answer, not a failure: the same request detects a planted long and a '
                'planted short through this exact path, so an empty result is a reading of the '
                'evidence. Nothing is shown here rather than the two least-bad names, because a '
                'top two taken from names the model declined is a pick manufactured out of ties.</p>'
                f'<p class="note">{OPPORTUNITY_NOTE}</p></section>')

    engine_only = comparison.get('engine_only') or []
    tail = ''
    if engine_only:
        tail = ('<p class="sub" style="border:none;padding:0">The engine\'s own board today: '
                + escape(', '.join(engine_only)) + ' — none of which the model picked.</p>')
    return (head + kv
            + '<div class="scroll"><table><caption>Confidence is the model\'s own stated number. '
              'It is NOT a calibrated win probability, has no track record, and has never been '
              'scored against an outcome. The engine column is its sided probability, a different '
              'quantity on a different scale; they are printed together for comparison and are '
              'never combined.</caption>'
              '<thead><tr><th>Side</th><th>Name</th><th class="num">Model confidence</th>'
              '<th class="num">Engine sided</th><th>Do they agree?</th>'
              '<th>Why — the model\'s words, not verified fact</th></tr></thead>'
            + f'<tbody>{_opportunity_rows(comparison)}</tbody></table></div>'
            + tail + f'<p class="note">{OPPORTUNITY_NOTE}</p></section>')


def _gap_items(digest):
    """Every gap the frozen computation recorded, in the reader's language."""
    intra = digest['intraday']
    res = intra.get('res') or {}
    items = []
    gap = R.record_gap_line(intra.get('record') or {})
    if gap:
        items.append(('alarm', gap))
    items += [('accent', line) for line in R.cache_lines(res)]
    if res.get('coverage_fail'):
        items.append(('alarm', str(res['coverage_fail'])))
    note = R.factor_note(intra)
    if note:
        items.append(('quiet', note))
    exact = intra.get('exact_record') or {}
    if not exact.get('scored_legs'):
        items.append(('quiet', 'Exact net/index evidence is not yet accumulating — matched '
                               '09:46/15:59 execution quotes are required and none are recorded.'))
    for err in digest.get('errors') or []:
        items.append(('caution', f"{err.get('layer', 'acquisition')} — {R.plain_fault(err)}"))
    for err in (digest.get('biotech') or {}).get('errors') or []:
        items.append(('caution', 'biotech — '+R.plain_fault({'error': err})))
    return items


def render(digest):
    """Frozen digest in, complete HTML page out. Pure."""
    intra = digest['intraday']
    res = intra.get('res') or {}
    record = intra.get('record') or {}
    rate = (intra.get('risk_evidence') or {}).get('rate') or {}
    legs = intra.get('legs') or []
    entry = _is_entry(digest)
    generated = str(digest.get('generated_at', ''))[11:19]
    commit = str((digest.get('provenance') or {}).get('code_commit') or 'not recorded')[:12]

    banner = '' if entry else f'''
    <div class="notice">
      <h2>Not an executable entry</h2>
      <p>{escape(str(digest.get('report_status', '')))}. The 09:46 entry window is the only
      moment this board's reference prices are executable; outside it this page is a record of
      what the engine computed, not an instruction. No share count or allocation is rendered on
      an abstained leg.</p>
    </div>'''

    gaps = '\n'.join(
        f'<li class="g-{kind}">{escape(str(text))}</li>' for kind, text in _gap_items(digest))

    return f'''<title>RB Report {escape(str(digest.get("session", "")))}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,500;6..72,600&family=IBM+Plex+Mono:wght@400;500;600&family=IBM+Plex+Sans:wght@400;500;600&display=swap">
<style>
:root {{
  --ground:#f6f8f5; --surface:#fff; --sunk:#eef1ed; --ink:#191d1a; --ink-soft:#4e5650;
  --ink-mute:#767f77; --rule:#d7ddd6; --rule-soft:#e6eae4; --accent:#2c5e59;
  --accent-soft:#e2edea; --withheld:#8a9089; --caution:#8a5f19; --caution-bg:#f7efe0;
  --alarm:#8b2f2f; --alarm-bg:#f6e8e6;
  --measure:68ch; --serif:"Newsreader",Georgia,serif;
  --sans:"IBM Plex Sans",system-ui,sans-serif; --mono:"IBM Plex Mono",ui-monospace,Menlo,monospace;
}}
@media (prefers-color-scheme:dark) {{ :root:not([data-theme="light"]) {{
  --ground:#131715; --surface:#1a1f1c; --sunk:#101413; --ink:#e4e9e3; --ink-soft:#a9b2ab;
  --ink-mute:#7d867f; --rule:#2b322d; --rule-soft:#232925; --accent:#6fb3a9;
  --accent-soft:#1d2b29; --withheld:#7a827b; --caution:#d0a25c; --caution-bg:#2a2317;
  --alarm:#d98a80; --alarm-bg:#2b1c1a;
}} }}
:root[data-theme="dark"] {{
  --ground:#131715; --surface:#1a1f1c; --sunk:#101413; --ink:#e4e9e3; --ink-soft:#a9b2ab;
  --ink-mute:#7d867f; --rule:#2b322d; --rule-soft:#232925; --accent:#6fb3a9;
  --accent-soft:#1d2b29; --withheld:#7a827b; --caution:#d0a25c; --caution-bg:#2a2317;
  --alarm:#d98a80; --alarm-bg:#2b1c1a;
}}
*{{box-sizing:border-box}}
body{{background:var(--ground);color:var(--ink);font-family:var(--serif);line-height:1.6;
  margin:0;padding-block:0 4rem;padding-left:max(20px,env(safe-area-inset-left));
  padding-right:max(20px,env(safe-area-inset-right));-webkit-font-smoothing:antialiased}}
.wrap{{max-width:78ch;margin:0 auto}}
.masthead{{border-bottom:2px solid var(--ink);padding-block:2.5rem 1rem}}
.kicker{{font-family:var(--sans);font-size:.8125rem;font-weight:600;letter-spacing:.13em;
  text-transform:uppercase;color:var(--accent);margin:0 0 .6rem}}
h1{{font-weight:500;font-size:2.75rem;line-height:1.08;letter-spacing:-.02em;margin:0;text-wrap:balance}}
.dateline{{font-family:var(--mono);font-size:.8125rem;color:var(--ink-soft);display:flex;
  flex-wrap:wrap;gap:.4rem 1.2rem;margin:.9rem 0 0}}
.notice{{border:1px solid var(--rule);border-left:3px solid var(--caution);background:var(--caution-bg);
  padding:1.1rem 1.25rem;margin-block:1.75rem}}
.notice h2{{font-family:var(--sans);font-size:.8125rem;font-weight:600;letter-spacing:.1em;
  text-transform:uppercase;color:var(--caution);margin:0 0 .5rem}}
.notice p{{margin:0;font-size:.95rem;line-height:1.55;max-width:var(--measure)}}
section{{margin-block:3.25rem}}
h2.head{{font-weight:600;font-size:1.5rem;letter-spacing:-.01em;margin:0 0 .25rem;text-wrap:balance}}
.sub{{font-family:var(--sans);font-size:.8125rem;color:var(--ink-mute);margin:0 0 1.5rem;
  padding-bottom:.75rem;border-bottom:1px solid var(--rule)}}
p{{margin:0 0 1rem;max-width:var(--measure)}}
.scroll{{overflow-x:auto;margin-block:1.25rem;border:1px solid var(--rule);background:var(--surface)}}
table{{border-collapse:collapse;width:100%;font-family:var(--mono);font-size:.8125rem}}
th,td{{padding:.6rem 1rem;text-align:left;border-bottom:1px solid var(--rule-soft);white-space:nowrap}}
thead th{{font-family:var(--sans);font-size:.75rem;font-weight:600;letter-spacing:.07em;
  text-transform:uppercase;color:var(--ink-mute);background:var(--sunk);border-bottom:1px solid var(--rule)}}
tbody tr:last-child td{{border-bottom:none}}
.num{{text-align:right;font-variant-numeric:tabular-nums}}
.tick{{font-weight:600}}
.withheld{{color:var(--withheld)}}
.empty{{white-space:normal;color:var(--ink-soft);font-family:var(--sans);line-height:1.5}}
.reason td{{white-space:normal;font-family:var(--sans);font-size:.78rem;color:var(--ink-mute);
  padding-top:0;border-bottom:1px solid var(--rule-soft)}}
.status{{font-family:var(--sans);font-size:.72rem;font-weight:600;letter-spacing:.06em;
  text-transform:uppercase;padding:.15rem .5rem;border:1px solid currentColor;color:var(--withheld)}}
.ci{{background:var(--surface);border:1px solid var(--rule);padding:1.5rem 1.25rem 1.25rem;margin:1.25rem 0}}
.ci-track{{position:relative;height:46px;margin:2rem 0 .25rem}}
.ci-axis{{position:absolute;inset:auto 0 0;height:1px;background:var(--rule)}}
.ci-band{{position:absolute;top:14px;height:18px;background:var(--accent-soft);border:1px solid var(--accent)}}
.ci-point{{position:absolute;top:8px;width:2px;height:30px;background:var(--accent)}}
.ci-coin{{position:absolute;top:0;bottom:0;width:1px;background:var(--alarm)}}
.ci-coin::after{{content:"coin flip · 50%";position:absolute;top:-1.35rem;left:50%;
  transform:translateX(-50%);white-space:nowrap;font-family:var(--sans);font-size:.72rem;
  font-weight:600;color:var(--alarm)}}
.ci-label{{position:absolute;top:36px;font-family:var(--mono);font-size:.72rem;color:var(--accent);
  transform:translateX(-50%);white-space:nowrap}}
.ci-mid{{font-weight:600}}
.ci-ticks{{display:flex;justify-content:space-between;font-family:var(--mono);font-size:.72rem;
  color:var(--ink-mute);font-variant-numeric:tabular-nums}}
figcaption{{font-family:var(--sans);font-size:.85rem;color:var(--ink-soft);margin-top:1.25rem;
  max-width:var(--measure);line-height:1.55}}
.kv{{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:1px;
  background:var(--rule);border:1px solid var(--rule);margin-block:1.25rem}}
.kv>div{{background:var(--surface);padding:.9rem 1rem}}
.kv dt{{font-family:var(--sans);font-size:.72rem;font-weight:600;letter-spacing:.07em;
  text-transform:uppercase;color:var(--ink-mute);margin:0 0 .3rem}}
.kv dd{{font-family:var(--mono);font-size:1.2rem;margin:0;font-variant-numeric:tabular-nums}}
.kv dd small{{font-family:var(--sans);font-size:.75rem;color:var(--ink-mute);display:block;
  margin-top:.15rem;font-variant-numeric:normal}}
ul.gaps{{list-style:none;padding:0;margin:1.25rem 0}}
ul.gaps li{{border-left:3px solid var(--rule);background:var(--surface);padding:.75rem 1rem;
  margin-bottom:1px;font-family:var(--sans);font-size:.88rem;line-height:1.55}}
.g-alarm{{border-left-color:var(--alarm);background:var(--alarm-bg)}}
.g-caution{{border-left-color:var(--caution);background:var(--caution-bg)}}
.g-accent{{border-left-color:var(--accent);background:var(--accent-soft)}}
.g-quiet{{border-left-color:var(--rule)}}
.reasontext{{white-space:normal;font-family:var(--sans);font-size:.8rem;color:var(--ink-soft);
  line-height:1.5;min-width:22ch}}
.note{{font-family:var(--sans);font-size:.85rem;color:var(--ink-mute);line-height:1.55}}
footer{{border-top:2px solid var(--ink);margin-top:3.5rem;padding-top:1.25rem;
  font-family:var(--mono);font-size:.75rem;color:var(--ink-mute);display:flex;
  flex-wrap:wrap;gap:.35rem 1.5rem}}
@media (max-width:480px){{h1{{font-size:2.1rem}}}}
@media (prefers-reduced-motion:reduce){{*{{animation:none!important;transition:none!important}}}}
</style>
<div class="wrap">
  <header class="masthead">
    <p class="kicker">{'Morning entry board' if entry else 'Informational · not an entry'}</p>
    <h1>RB Daily Report</h1>
    <div class="dateline">
      <span>Session {escape(str(digest.get('session','')))}</span>
      <span>Snapshot {escape(generated)} ET</span>
      <span>Code {escape(commit)}</span>
      <span>TSX · CAD</span>
    </div>
  </header>
  {banner}

  <section>
    <h2 class="head">Part 1 · Intraday</h2>
    <p class="sub">{escape(str(intra.get('contract','')))} · signal reference is the 09:45 completed bar</p>
    <p>{escape(str(intra.get('model_claim','')))}</p>
    <div class="scroll"><table>
      <thead><tr><th>Status</th><th>Name</th><th>Side</th><th class="num">09:45 bar</th>
        <th class="num">09:46 quote</th><th class="num">Spread bps</th><th class="num">Shares</th></tr></thead>
      <tbody>{_legs_rows(legs)}</tbody>
    </table></div>
    <p class="sub" style="border:none;padding:0">Evaluated {res.get('n_names', 0)} names ·
      {len(intra.get('recorded_today') or [])} recorded qualifiers ·
      source {escape(str(res.get('source') or 'unavailable'))}</p>
  </section>

  {_opportunities_section(intra)}

  <section>
    <h2 class="head">How reliable is this record?</h2>
    <p class="sub">Gross hit rate, clustered by session</p>
    {_ci_figure(rate)}
    <div class="kv">
      <div><dt>Gross hits</dt><dd>{record.get('hits', 0)} / {record.get('n', 0)}
        <small>{_pct(record.get('rate'))}</small></dd></div>
      <div><dt>Mean capture</dt><dd>{fmt(record.get('mean'), '+.3f')}%<small>per leg, gross</small></dd></div>
      <div><dt>Net-priced legs</dt><dd>{record.get('net_n', 0)}
        <small>{record.get('net_unpriced', 0)} unpriced</small></dd></div>
      <div><dt>Net mean</dt><dd>{fmt(record.get('net_mean'), '+.3f')}%<small>where spread is stored</small></dd></div>
    </div>
    <p>An analog score is a diagnostic, not a calibrated win probability. Hit counts do not
      measure loss size: the ratio of average win to average loss is what decides whether a
      48.6% hit rate makes or loses money.</p>
    <h2 class="head" style="font-size:1.2rem;margin-top:2rem">Calibration by score band</h2>
    <div class="scroll"><table>
      <thead><tr><th>Band</th><th class="num">Hits</th><th class="num">Legs</th>
        <th class="num">Sessions</th><th class="num">Observed</th><th class="num">MDE80</th></tr></thead>
      <tbody>{_calibration_rows((intra.get('risk_evidence') or {}).get('calibration'))}</tbody>
    </table></div>
  </section>

  {_factor_section(intra)}

  <section>
    <h2 class="head">Gaps and faults</h2>
    <p class="sub">Everything the computation could not establish, stated once</p>
    <ul class="gaps">{gaps or '<li>No gaps recorded.</li>'}</ul>
  </section>

  <footer>
    <span>Read-only research · no order was placed</span>
    <span>Code {escape(commit)}</span>
    <span>Schema v{digest.get('schema_version', '?')}</span>
  </footer>
</div>'''


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--report', required=True, help='frozen report.json from daily_job')
    p.add_argument('--output', required=True, help='HTML file to write')
    a = p.parse_args(argv)
    with open(a.report) as handle:
        digest = json.load(handle)
    with open(a.output, 'w') as handle:
        handle.write(render(digest))
    print(a.output)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
